version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile/postgres.Dockerfile
    ports:
      - "5431:5432"
    volumes: 
      - app_db_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile/Django.Dockerfile
    ports: 
      - "8002:8001"

volumes:
  app_db_data: