version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile/postgres.Dockerfile
    ports:
      - "5431:5432"
    volumes: 
      - app_db_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile/Django.Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - db_name=${db_name}
      - db_user=${db_user}
      - db_PASSWORD=${SECRET_KEY}
      - db_HOST=${db_HOST}
      - db_PORT=${db_PORT}
    ports: 
      - "8002:8001"

volumes:
  app_db_data: