name: Project Pipeline
on:
  push:
    branches:
      - develop
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create .env
        env:
          SECRET_KEY: ${{secrets.DB_SECRET_KEY}}
          db_PASSWORD: ${{secrets.DB_PASSWORD}}
          db_name: ${{secrets.DB_NAME}}
          db_user: ${{secrets.DB_USER}}
          db_HOST: ${{secrets.DB_HOST}}
          db_PORT: ${{secrets.DB_PORT}}

        run: |
          $v = @"
          SECRET_KEY=$env:SECRET_KEY
          db_name=$env:db_name
          db_user=$env:db_user
          db_PASSWORD=$env:db_PASSWORD
          db_HOST=$env:db_HOST
          db_PORT=$env:db_PORT
          "@
          $v | Out-File -Encoding ASCII .env
                    
      - name: Build and start Docker compose services
        run: |
          ls
          docker compose -f docker-compose.yml up --build -d
          sleep 20
          
      - name: Run Django tests
        run: docker exec web python ./app/tooplat/manage.py test



