name: Project Pipeline
on:
  push:
    branches:
      - develop
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and start Docker compose services
        env:
          SECRET_KEY: ${{secrets.DB_SECRET_KEY}}
          db_PASSWORD: ${{secrets.DB_PASSWORD}}
          db_name: ${{secrets.DB_NAME}}
          db_user: ${{secrets.DB_USER}}
          db_HOST: ${{secrets.DB_HOST}}
          db_PORT: ${{secrets.DB_PORT}}
        run: docker compose -f docker-compose.yml up -d


      - name: Run Django tests
        run: docker compose exec web python ./tooplat/manage.py test

      - name: Finally stop docker compose
        run: docker compose -f docker-compose.yml down